xdia-loader(DIA2Dump): fix build with recent musl
Since xdia-loader is meant to be run under blink, it is attractive
to build it static with a minimal runtime. This fixes musl libc.

Specifically:

/usr/include/c++/15.2.0/bits/stl_algobase.h:282:56: error: macro 'min' passed 3 arguments, but takes just 2
  282 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |                                                        ^
In file included from /build/source/src/../include/wine/windows.h:38,
                 from /build/source/src/../include/wine/rpc.h:22,
                 from /build/source/src/../include/dia/dia2.h:22,
                 from /build/source/src/DIA2Dump/stdafx.h:17,
                 from /build/source/src/DIA2Dump/DIA2Dump.cpp:17:
/build/source/src/../include/wine/windef.h:355:9: note: macro 'min' defined here
  355 | #define min(a,b)   (((a) < (b)) ? (a) : (b))
      |         ^~~

Clearly, trying to get the windows headers and the gcc stdlib headers to
play nice is a fool's errand, so we hackfix the issue by forcing this
header to import prior to the inclusion of windows.h.